modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="zombie_apocalypse"
version="pre alpha"
displayName="zombie apocalypse +"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="robotridragon"
description='''
more zombies! and items!
'''

[[dependencies.zombie_apocalypse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




